### ISSUE TITLE
Build fails for 'lumin' target

### ISSUE THREAD

**Issue by FrozenKiwi** [magicleap/c_api_samples#3]
Building with python script works, builds are generated as advertised.

When building the samples manually, I tried
`mabu simple-gl-app.mabu -t lumin`
However we get the following error:
`.../include\app_framework/resource_pool.inl:15:10: fatal error: 'assimp/Importer.hpp' file not found`

Looking into the python, it uses the following target `ml1_clang-8`, which I guess is using a newer version of clang.

Is this expected?  If so, can we get the documentation/other tools updated?  Specifically, I'm building a native plugin for Unity and it must use the `-t lumin` target.  It's been quite a few hours figuring out what was supposed to be happening

**Comment by stevebu56** [comment]
Yes `ml1_clang-8` is the version that should be used, that is expected.  Looks like when specifying the single mabu to build it drops down to the old version which is a bug in this case.  In the meantime you can do the following to get it built.  

Build everything from the top level `samples` dir.  
`python build.py`

Build the single mabu specifying the target. Note you can specify the `.package` or `.mabu` file.
`mabu -t ml1_clang-8 simple_gl_app/com.magicleap.capi.sample.simple_gl_app.package`
